raise ValueError('A very specific error occur')
